### ISSUE TITLE
Add installation instructions in the readme

### ISSUE THREAD

**Issue by beausmith** [konnected-io/noonlight-hass#9]
Home Assistant has evolved and it seems that this is not an officially supported integration and thus is not listed among the official integrations which can be added easily. 

However the fact that a `hacs.json` file exists lead me to install [HACS](https://hacs.xyz/) in order to get this support in home assistant. 

I did also use the [Manual Alarm Control](https://www.home-assistant.io/integrations/manual/) to complete the integration.

So the process was:

1. Install Konnected.io integration, attach sensors to the boards, and configure the boards.
2. Install HACS.
2. Install `noonlight-hass` via HACS.
3. Add a `noonlight` entry to the `configuration.yaml` file:
    ```
    # Noonlight
    noonlight:
      id: YOUR_ID_HERE
      secret: YOUR_SECRET_HERE
      api_endpoint: https://api.noonlight.com/platform/v1
      token_endpoint: https://noonlight.konnected.io/ha/token
    ```
4. Install integration for the [Manual Alarm Control](https://www.home-assistant.io/integrations/manual/)
5. Add config for the Manual alarm control the the `configuration.yaml` file:
    ````
    alarm_control_panel:
      - platform: manual
    ````
6. Create Automation to call Noonlight if the Manual alarm is triggered:
    <img width="540" alt="konnected-noonlight-automation" src="https://user-images.githubusercontent.com/28444/121580376-861ffd00-c9e1-11eb-9867-3d2ab624358a.png">
    Here is the YAML version automatically created from the UI above:
    ```
    alias: Noonlight Alarm
    description: ''
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: triggered
    condition: []
    action:
      - service: homeassistant.turn_on
        target:
          entity_id: switch.noonlight_switch
    mode: single
    ```
    At this point you can manually trigger the automation test that the integration between the Manual alarm and Noonlight is working. 

7. Create automations to trigger the manual alarm if various sensors connected to the Konnected.io board change. This step is not detailed here because it will be different based upon what sensors you have.
